export default [
  {
    id: '1',
    name: "Kroger Whole Milk",
    serNum: "844535622745",
    price: "2.89",
    manufacturer: "Kroger",
    category: "milk",
    quantity: 20,
    image: "./images/kroger_milk.jpg",
    inCart: false,
    filtered: false
  },
  {
    id: '2',
    name: "Simple Truth Whole Milk",
    serNum: "522397798442",
    price: "3.29",
    manufacturer: "Simple Truth",
    category: "milk",
    quantity: 15,
    image: "./images/simple_truth_milk.jpg",
    inCart: false,
    filtered: false
  },
  {
    id: '3',
    name: "Simple Truth Eggs",
    serNum: "342448254324",
    price: "2.79",
    manufacturer: "Simple Truth",
    category: "eggs",
    quantity: 31,
    image: "./images/simple_truth_eggs.jpg",
    inCart: false,
    filtered: false
  },
  {
    id: '4',
    name: "Kroger Eggs",
    serNum: "382698339956",
    price: "1.09",
    manufacturer: "Kroger",
    category: "eggs",
    quantity: 26,
    image: "./images/kroger_eggs.jpg",
    inCart: false,
    filtered: false
  },
  {
    id: '5',
    name: "Honeycrisp Apples",
    serNum: "563328883845",
    price: "1.95",
    manufacturer: "Texas Local Farm",
    category: "fruit",
    quantity: 63,
    image: "./images/honeycrisp_apple.jpg",
    inCart: false,
    filtered: false
  },
  {
    id: '6',
    name: "Navel Oranges",
    serNum: "334932937535",
    price: "0.79",
    manufacturer: "Texas Local Farm",
    category: "fruit",
    quantity: 59,
    image: "./images/navel_oranges.jpg",
    inCart: false,
    filtered: false
  },
  {
    id: '7',
    name: "Heritage Farm Chicken Breasts",
    serNum: "276446552347",
    price: "9.42",
    manufacturer: "Heritage Farm",
    category: "meat",
    quantity: 8,
    image: "./images/heritage_farm_chicken_breasts.jpg",
    inCart: false,
    filtered: false
  },
  {
    id: '8',
    name: "Simple Truth Ground Beef",
    serNum: "378892473375",
    price: "7.99",
    manufacturer: "Simple Truth",
    category: "meat",
    quantity: 12,
    image: "./images/simple_truth_ground_beef.jpg",
    inCart: false,
    filtered: false
  },
  {
    id: '9',
    name: "Sand Bar Cooked Shrimp",
    serNum: "762356735484",
    price: "19.99",
    manufacturer: "Sand Bar",
    category: "seafood",
    quantity: 7,
    image: "./images/sand_bar_cooked_shrimp.jpg",
    inCart: false,
    filtered: false
  },
  {
    id: '10',
    name: "Folgers Classic Roast Coffee",
    serNum: "852872243892",
    price: "7.99",
    manufacturer: "Folgers",
    category: "coffee",
    quantity: 17,
    image: "./images/folgers_classic_roast_coffee.jpg",
    inCart: false,
    filtered: false
  },
  {
    id: '11',
    name: "Starbucks Pike Place Coffee",
    serNum: "754275747297",
    price: "7.29",
    manufacturer: "Starbucks",
    category: "coffee",
    quantity: 14,
    image: "./images/starbucks_pike_place_coffee.jpg",
    inCart: false,
    filtered: false
  },
  {
    id: '12',
    name: "Bananas",
    serNum: "484599495727",
    price: "0.28",
    manufacturer: "Texas Local Farm",
    category: "fruit",
    quantity: 158,
    image: "./images/bananas.jpg",
    inCart: false,
    filtered: false
  },
  {
    id: '13',
    name: "Broccoli",
    serNum: "256568983768",
    price: "1.03",
    manufacturer: "Texas Local Farm",
    category: "vegetable",
    quantity: 86,
    image: "./images/broccoli.jpg",
    inCart: false,
    filtered: false
  },
  {
    id: '14',
    name: "Kroger Apple Juice",
    serNum: "242856279969",
    price: "1.50",
    manufacturer: "Kroger",
    category: "juice",
    quantity: 35,
    image: "./images/kroger_apple_juice.jpg",
    inCart: false,
    filtered: false
  },
  {
    id: '15',
    name: "Snickers Bar",
    serNum: "632948747245",
    price: "0.99",
    manufacturer: "Snickers",
    category: "candy",
    quantity: 72,
    image: "./images/snickers_bar.jpg",
    inCart: false,
    filtered: false
  },
  {
    id: '16',
    name: "Reese's Peanut Butter Cup",
    serNum: "953345782394",
    price: "1.00",
    manufacturer: "Reese's",
    category: "candy",
    quantity: 64,
    image: "./images/reeses_peanut_butter_cup.jpg",
    inCart: false,
    filtered: false
  },
  {
    id: '17',
    name: "Kroger Orange Juice",
    serNum: "923392768974",
    price: "2.49",
    manufacturer: "Kroger",
    category: "juice",
    quantity: 29,
    image: "./images/kroger_orange_juice.jpg",
    inCart: false,
    filtered: false
  },
  {
    id: '18',
    name: "Salmon Atlantic Fillet",
    serNum: "879797835495",
    price: "10.71",
    manufacturer: "Texas Local Farm",
    category: "seafood",
    quantity: 13,
    image: "./images/salmon_atlantic_fillet.jpg",
    inCart: false,
    filtered: false
  }
]